import type { Pillar } from '../types';

export const PILLARS: Pillar[] = [
  {
    id: 'mind',
    label: 'Mind',
    description: 'Cognition, learning, focus, worldview',
    color: '#6C63FF',
    icon: '🧠',
    northStarMetrics: [
      {
        id: 'mind_deep_work_quality',
        pillar: 'mind',
        label: 'Deep Work Quality',
        description: 'Overall cognitive clarity score for the week',
        type: 'score',
        isNorthStar: true,
      },
      {
        id: 'mind_decision_quality',
        pillar: 'mind',
        label: 'Decision Quality',
        description: '% of important decisions still endorsed after 2 weeks',
        type: 'percentage',
        isNorthStar: true,
      },
    ],
    leadingMetrics: [
      {
        id: 'mind_deep_work_minutes',
        pillar: 'mind',
        label: 'Deep Work Minutes',
        description: 'Minutes in focused 45–90 min blocks',
        type: 'duration',
        unit: 'min',
        isLeading: true,
      },
      {
        id: 'mind_learning_minutes',
        pillar: 'mind',
        label: 'Learning Minutes',
        description: 'Deliberate study, not scrolling',
        type: 'duration',
        unit: 'min',
        isLeading: true,
      },
      {
        id: 'mind_distraction_breaches',
        pillar: 'mind',
        label: 'Distraction Breaches',
        description: 'Times you broke focus today',
        type: 'count',
        isLeading: true,
      },
      {
        id: 'mind_decision_journal',
        pillar: 'mind',
        label: 'Decision Journal Entry',
        description: 'Did you log a decision today?',
        type: 'boolean',
        isLeading: true,
      },
    ],
    optionalMetrics: [
      {
        id: 'mind_strategic_review',
        pillar: 'mind',
        label: 'Strategic Review Done',
        description: 'Weekly strategic review completed',
        type: 'boolean',
      },
    ],
  },
  {
    id: 'emotion',
    label: 'Emotion',
    description: 'Regulation, resilience, stress management',
    color: '#FF6584',
    icon: '❤️',
    northStarMetrics: [
      {
        id: 'emotion_stability',
        pillar: 'emotion',
        label: 'Emotional Stability',
        description: 'How stable your mood has been',
        type: 'score',
        isNorthStar: true,
      },
    ],
    leadingMetrics: [
      {
        id: 'emotion_protocol_used',
        pillar: 'emotion',
        label: 'Regulation Protocol Used',
        description: 'Used breathing, walk, or urge surfing when triggered?',
        type: 'boolean',
        isLeading: true,
      },
      {
        id: 'emotion_outbursts',
        pillar: 'emotion',
        label: 'Impulsive Actions',
        description: 'Emotional outbursts or impulsive actions today',
        type: 'count',
        isLeading: true,
      },
      {
        id: 'emotion_stress',
        pillar: 'emotion',
        label: 'Stress Level',
        description: 'Stress rating (0–10)',
        type: 'score',
        isLeading: true,
      },
      {
        id: 'emotion_meditation_minutes',
        pillar: 'emotion',
        label: 'Stillness Minutes',
        description: 'Meditation or regulation practice minutes',
        type: 'duration',
        unit: 'min',
        isLeading: true,
      },
    ],
    optionalMetrics: [],
  },
  {
    id: 'body',
    label: 'Body',
    description: 'Health, fitness, energy, recovery',
    color: '#43D9AD',
    icon: '⚡',
    northStarMetrics: [
      {
        id: 'body_energy',
        pillar: 'body',
        label: 'Energy Score',
        description: 'Overall energy and vitality (0–10)',
        type: 'score',
        isNorthStar: true,
      },
    ],
    leadingMetrics: [
      {
        id: 'body_sleep_hours',
        pillar: 'body',
        label: 'Sleep Hours',
        description: 'Hours of sleep last night',
        type: 'duration',
        unit: 'hrs',
        isLeading: true,
      },
      {
        id: 'body_training',
        pillar: 'body',
        label: 'Training Session',
        description: 'Did you train today?',
        type: 'boolean',
        isLeading: true,
      },
      {
        id: 'body_steps',
        pillar: 'body',
        label: 'Steps / Active Minutes',
        description: 'Active movement today',
        type: 'count',
        isLeading: true,
      },
      {
        id: 'body_protein',
        pillar: 'body',
        label: 'Protein Target Hit',
        description: 'Hit your protein goal today?',
        type: 'boolean',
        isLeading: true,
      },
      {
        id: 'body_substances',
        pillar: 'body',
        label: 'Substance Use',
        description: 'Alcohol/tobacco/cannabis today (0 = clean)',
        type: 'count',
        isLeading: true,
      },
    ],
    optionalMetrics: [
      {
        id: 'body_rhr',
        pillar: 'body',
        label: 'Resting Heart Rate',
        description: 'Resting HR in bpm',
        type: 'count',
        unit: 'bpm',
      },
    ],
  },
  {
    id: 'relationships',
    label: 'Relationships',
    description: 'Tribe, intimacy, trust, connection',
    color: '#FF9A3C',
    icon: '🤝',
    northStarMetrics: [
      {
        id: 'rel_quality',
        pillar: 'relationships',
        label: 'Relationship Quality',
        description: 'Overall relationship satisfaction (0–10)',
        type: 'score',
        isNorthStar: true,
      },
    ],
    leadingMetrics: [
      {
        id: 'rel_conversations',
        pillar: 'relationships',
        label: 'Meaningful Conversations',
        description: '≥15 min conversations, no phones',
        type: 'count',
        isLeading: true,
      },
      {
        id: 'rel_outreach',
        pillar: 'relationships',
        label: 'Outreach Initiated',
        description: 'Messages or calls you initiated today',
        type: 'count',
        isLeading: true,
      },
      {
        id: 'rel_repair',
        pillar: 'relationships',
        label: 'Repair Attempt',
        description: 'Did you repair friction within 24–48h?',
        type: 'boolean',
        isLeading: true,
      },
    ],
    optionalMetrics: [],
  },
  {
    id: 'vocation',
    label: 'Vocation',
    description: 'Craft, career, output, leverage',
    color: '#3C9EFF',
    icon: '⚔️',
    northStarMetrics: [
      {
        id: 'voc_output',
        pillar: 'vocation',
        label: 'Output Shipped',
        description: 'Deliverables completed this week',
        type: 'count',
        isNorthStar: true,
      },
    ],
    leadingMetrics: [
      {
        id: 'voc_deep_work_hours',
        pillar: 'vocation',
        label: 'Craft Deep Work Hours',
        description: 'Hours on core skill development',
        type: 'duration',
        unit: 'hrs',
        isLeading: true,
      },
      {
        id: 'voc_shipped',
        pillar: 'vocation',
        label: 'Deliverable Shipped',
        description: 'Did you ship something today?',
        type: 'boolean',
        isLeading: true,
      },
      {
        id: 'voc_high_leverage',
        pillar: 'vocation',
        label: 'High-Leverage Task',
        description: 'Completed your most important task?',
        type: 'boolean',
        isLeading: true,
      },
    ],
    optionalMetrics: [],
  },
  {
    id: 'wealth',
    label: 'Wealth',
    description: 'Net worth, savings, income, financial discipline',
    color: '#A8FF78',
    icon: '💎',
    northStarMetrics: [
      {
        id: 'wealth_savings_rate',
        pillar: 'wealth',
        label: 'Savings Rate',
        description: '% of income saved this month',
        type: 'percentage',
        isNorthStar: true,
      },
    ],
    leadingMetrics: [
      {
        id: 'wealth_spend_tracked',
        pillar: 'wealth',
        label: 'Spend Tracked',
        description: 'Did you log your spending today?',
        type: 'boolean',
        isLeading: true,
      },
      {
        id: 'wealth_investing',
        pillar: 'wealth',
        label: 'Automated Investing',
        description: 'Investing action executed today?',
        type: 'boolean',
        isLeading: true,
      },
      {
        id: 'wealth_no_dumb_purchases',
        pillar: 'wealth',
        label: 'No Dumb Purchases',
        description: 'Avoided impulsive spending today?',
        type: 'boolean',
        isLeading: true,
      },
    ],
    optionalMetrics: [],
  },
  {
    id: 'adventure',
    label: 'Adventure',
    description: 'Experiences, creativity, aliveness',
    color: '#FF6B6B',
    icon: '🔥',
    northStarMetrics: [
      {
        id: 'adv_aliveness',
        pillar: 'adventure',
        label: 'Aliveness Score',
        description: 'How alive and engaged you feel (0–10)',
        type: 'score',
        isNorthStar: true,
      },
    ],
    leadingMetrics: [
      {
        id: 'adv_novel_experiences',
        pillar: 'adventure',
        label: 'Novel Experiences',
        description: 'New places, skills, or social contexts today',
        type: 'count',
        isLeading: true,
      },
      {
        id: 'adv_creation_minutes',
        pillar: 'adventure',
        label: 'Creation Minutes',
        description: 'Minutes making > consuming',
        type: 'duration',
        unit: 'min',
        isLeading: true,
      },
      {
        id: 'adv_discomfort_reps',
        pillar: 'adventure',
        label: 'Discomfort Reps',
        description: 'Did something hard or uncomfortable today?',
        type: 'count',
        isLeading: true,
      },
    ],
    optionalMetrics: [],
  },
];

export const PILLAR_MAP = Object.fromEntries(
  PILLARS.map((p) => [p.id, p])
) as Record<string, Pillar>;

export const ALL_METRICS = PILLARS.flatMap((p) => [
  ...p.northStarMetrics,
  ...p.leadingMetrics,
  ...p.optionalMetrics,
]);

export const METRIC_MAP = Object.fromEntries(
  ALL_METRICS.map((m) => [m.id, m])
);
